/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as StrikeTableRouteImport } from './routes/strike-table'
import { Route as StrikeChartRouteImport } from './routes/strike-chart'
import { Route as ScalpingRouteImport } from './routes/scalping'
import { Route as Nifty50RouteImport } from './routes/nifty50'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntelV6RouteImport } from './routes/intel-v6'
import { Route as IntelV5RouteImport } from './routes/intel-v5'
import { Route as IntelV4RouteImport } from './routes/intel-v4'
import { Route as IntelV3RouteImport } from './routes/intel-v3'
import { Route as IntelV2RouteImport } from './routes/intel-v2'
import { Route as IntelBridgeRouteImport } from './routes/intel-bridge'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as CustomChartRouteImport } from './routes/custom-chart'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Nifty50TradesRouteImport } from './routes/nifty50/trades'
import { Route as Nifty50AccountReportRouteImport } from './routes/nifty50/account-report'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const StrikeTableRoute = StrikeTableRouteImport.update({
  id: '/strike-table',
  path: '/strike-table',
  getParentRoute: () => rootRouteImport,
} as any)
const StrikeChartRoute = StrikeChartRouteImport.update({
  id: '/strike-chart',
  path: '/strike-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalpingRoute = ScalpingRouteImport.update({
  id: '/scalping',
  path: '/scalping',
  getParentRoute: () => rootRouteImport,
} as any)
const Nifty50Route = Nifty50RouteImport.update({
  id: '/nifty50',
  path: '/nifty50',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelV6Route = IntelV6RouteImport.update({
  id: '/intel-v6',
  path: '/intel-v6',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelV5Route = IntelV5RouteImport.update({
  id: '/intel-v5',
  path: '/intel-v5',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelV4Route = IntelV4RouteImport.update({
  id: '/intel-v4',
  path: '/intel-v4',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelV3Route = IntelV3RouteImport.update({
  id: '/intel-v3',
  path: '/intel-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelV2Route = IntelV2RouteImport.update({
  id: '/intel-v2',
  path: '/intel-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelBridgeRoute = IntelBridgeRouteImport.update({
  id: '/intel-bridge',
  path: '/intel-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomChartRoute = CustomChartRouteImport.update({
  id: '/custom-chart',
  path: '/custom-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Nifty50TradesRoute = Nifty50TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => Nifty50Route,
} as any)
const Nifty50AccountReportRoute = Nifty50AccountReportRouteImport.update({
  id: '/account-report',
  path: '/account-report',
  getParentRoute: () => Nifty50Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/chart': typeof ChartRoute
  '/custom-chart': typeof CustomChartRoute
  '/intel': typeof IntelRoute
  '/intel-bridge': typeof IntelBridgeRoute
  '/intel-v2': typeof IntelV2Route
  '/intel-v3': typeof IntelV3Route
  '/intel-v4': typeof IntelV4Route
  '/intel-v5': typeof IntelV5Route
  '/intel-v6': typeof IntelV6Route
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/nifty50': typeof Nifty50RouteWithChildren
  '/scalping': typeof ScalpingRoute
  '/strike-chart': typeof StrikeChartRoute
  '/strike-table': typeof StrikeTableRoute
  '/trade': typeof TradeRoute
  '/nifty50/account-report': typeof Nifty50AccountReportRoute
  '/nifty50/trades': typeof Nifty50TradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/chart': typeof ChartRoute
  '/custom-chart': typeof CustomChartRoute
  '/intel': typeof IntelRoute
  '/intel-bridge': typeof IntelBridgeRoute
  '/intel-v2': typeof IntelV2Route
  '/intel-v3': typeof IntelV3Route
  '/intel-v4': typeof IntelV4Route
  '/intel-v5': typeof IntelV5Route
  '/intel-v6': typeof IntelV6Route
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/nifty50': typeof Nifty50RouteWithChildren
  '/scalping': typeof ScalpingRoute
  '/strike-chart': typeof StrikeChartRoute
  '/strike-table': typeof StrikeTableRoute
  '/trade': typeof TradeRoute
  '/nifty50/account-report': typeof Nifty50AccountReportRoute
  '/nifty50/trades': typeof Nifty50TradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/chart': typeof ChartRoute
  '/custom-chart': typeof CustomChartRoute
  '/intel': typeof IntelRoute
  '/intel-bridge': typeof IntelBridgeRoute
  '/intel-v2': typeof IntelV2Route
  '/intel-v3': typeof IntelV3Route
  '/intel-v4': typeof IntelV4Route
  '/intel-v5': typeof IntelV5Route
  '/intel-v6': typeof IntelV6Route
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/nifty50': typeof Nifty50RouteWithChildren
  '/scalping': typeof ScalpingRoute
  '/strike-chart': typeof StrikeChartRoute
  '/strike-table': typeof StrikeTableRoute
  '/trade': typeof TradeRoute
  '/nifty50/account-report': typeof Nifty50AccountReportRoute
  '/nifty50/trades': typeof Nifty50TradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/chart'
    | '/custom-chart'
    | '/intel'
    | '/intel-bridge'
    | '/intel-v2'
    | '/intel-v3'
    | '/intel-v4'
    | '/intel-v5'
    | '/intel-v6'
    | '/login'
    | '/logs'
    | '/nifty50'
    | '/scalping'
    | '/strike-chart'
    | '/strike-table'
    | '/trade'
    | '/nifty50/account-report'
    | '/nifty50/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/chart'
    | '/custom-chart'
    | '/intel'
    | '/intel-bridge'
    | '/intel-v2'
    | '/intel-v3'
    | '/intel-v4'
    | '/intel-v5'
    | '/intel-v6'
    | '/login'
    | '/logs'
    | '/nifty50'
    | '/scalping'
    | '/strike-chart'
    | '/strike-table'
    | '/trade'
    | '/nifty50/account-report'
    | '/nifty50/trades'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/chart'
    | '/custom-chart'
    | '/intel'
    | '/intel-bridge'
    | '/intel-v2'
    | '/intel-v3'
    | '/intel-v4'
    | '/intel-v5'
    | '/intel-v6'
    | '/login'
    | '/logs'
    | '/nifty50'
    | '/scalping'
    | '/strike-chart'
    | '/strike-table'
    | '/trade'
    | '/nifty50/account-report'
    | '/nifty50/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ChartRoute: typeof ChartRoute
  CustomChartRoute: typeof CustomChartRoute
  IntelRoute: typeof IntelRoute
  IntelBridgeRoute: typeof IntelBridgeRoute
  IntelV2Route: typeof IntelV2Route
  IntelV3Route: typeof IntelV3Route
  IntelV4Route: typeof IntelV4Route
  IntelV5Route: typeof IntelV5Route
  IntelV6Route: typeof IntelV6Route
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  Nifty50Route: typeof Nifty50RouteWithChildren
  ScalpingRoute: typeof ScalpingRoute
  StrikeChartRoute: typeof StrikeChartRoute
  StrikeTableRoute: typeof StrikeTableRoute
  TradeRoute: typeof TradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strike-table': {
      id: '/strike-table'
      path: '/strike-table'
      fullPath: '/strike-table'
      preLoaderRoute: typeof StrikeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strike-chart': {
      id: '/strike-chart'
      path: '/strike-chart'
      fullPath: '/strike-chart'
      preLoaderRoute: typeof StrikeChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scalping': {
      id: '/scalping'
      path: '/scalping'
      fullPath: '/scalping'
      preLoaderRoute: typeof ScalpingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nifty50': {
      id: '/nifty50'
      path: '/nifty50'
      fullPath: '/nifty50'
      preLoaderRoute: typeof Nifty50RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-v6': {
      id: '/intel-v6'
      path: '/intel-v6'
      fullPath: '/intel-v6'
      preLoaderRoute: typeof IntelV6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-v5': {
      id: '/intel-v5'
      path: '/intel-v5'
      fullPath: '/intel-v5'
      preLoaderRoute: typeof IntelV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-v4': {
      id: '/intel-v4'
      path: '/intel-v4'
      fullPath: '/intel-v4'
      preLoaderRoute: typeof IntelV4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-v3': {
      id: '/intel-v3'
      path: '/intel-v3'
      fullPath: '/intel-v3'
      preLoaderRoute: typeof IntelV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-v2': {
      id: '/intel-v2'
      path: '/intel-v2'
      fullPath: '/intel-v2'
      preLoaderRoute: typeof IntelV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-bridge': {
      id: '/intel-bridge'
      path: '/intel-bridge'
      fullPath: '/intel-bridge'
      preLoaderRoute: typeof IntelBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-chart': {
      id: '/custom-chart'
      path: '/custom-chart'
      fullPath: '/custom-chart'
      preLoaderRoute: typeof CustomChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nifty50/trades': {
      id: '/nifty50/trades'
      path: '/trades'
      fullPath: '/nifty50/trades'
      preLoaderRoute: typeof Nifty50TradesRouteImport
      parentRoute: typeof Nifty50Route
    }
    '/nifty50/account-report': {
      id: '/nifty50/account-report'
      path: '/account-report'
      fullPath: '/nifty50/account-report'
      preLoaderRoute: typeof Nifty50AccountReportRouteImport
      parentRoute: typeof Nifty50Route
    }
  }
}

interface Nifty50RouteChildren {
  Nifty50AccountReportRoute: typeof Nifty50AccountReportRoute
  Nifty50TradesRoute: typeof Nifty50TradesRoute
}

const Nifty50RouteChildren: Nifty50RouteChildren = {
  Nifty50AccountReportRoute: Nifty50AccountReportRoute,
  Nifty50TradesRoute: Nifty50TradesRoute,
}

const Nifty50RouteWithChildren =
  Nifty50Route._addFileChildren(Nifty50RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ChartRoute: ChartRoute,
  CustomChartRoute: CustomChartRoute,
  IntelRoute: IntelRoute,
  IntelBridgeRoute: IntelBridgeRoute,
  IntelV2Route: IntelV2Route,
  IntelV3Route: IntelV3Route,
  IntelV4Route: IntelV4Route,
  IntelV5Route: IntelV5Route,
  IntelV6Route: IntelV6Route,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  Nifty50Route: Nifty50RouteWithChildren,
  ScalpingRoute: ScalpingRoute,
  StrikeChartRoute: StrikeChartRoute,
  StrikeTableRoute: StrikeTableRoute,
  TradeRoute: TradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
